# Generated by Django 5.1.2 on 2024-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.TextField(default='rahim'),
        ),
    ]
