# Generated by Django 5.1.2 on 2025-01-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='media/cars/'),
        ),
    ]
