# Generated by Django 5.1.2 on 2024-12-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('check_field', models.BooleanField(default=False)),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
